### PR TITLE
Archive all taps that are older than N-2

### PR DESCRIPTION
**Pull request by dsimansk**
To speed up verification and cluttering of the .rb files. IMO we can archive most of the older versions. 

Can be merged before: https://github.com/knative-extensions/homebrew-kn-plugins/pull/183

### CODE REVIEW

**Comment by dsimansk** [comment]
/hold

There are some older versions that have wrong formula format, probably better to fix them before archiving for good.

**Comment by rhuss** [comment]
@dsimansk thanks, I think that makes totally sense. However, looks like there are some conflicts to resolve right now.

**Comment by dsimansk** [comment]
> @dsimansk thanks, I think that makes totally sense. However, looks like there are some conflicts to resolve right now.

Yep, I've made the moves before fixing all the checksum etc. in the files. I'll sync the changes and rebase.

**Pull request merged**
